# Generated by Django 2.0.9 on 2024-12-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('reply_date', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fuel_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fuel_Price', models.CharField(max_length=100)),
                ('Fuel_Density', models.CharField(max_length=100)),
                ('Fuel_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fuel_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fuel_provider_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('Payment_Date', models.CharField(max_length=100)),
                ('Payment_Status', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('FUEL_PRICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.fuel_price')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login')),
            ],
        ),
        migrations.CreateModel(
            name='mechanic_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('Payment_Date', models.CharField(max_length=100)),
                ('Payment_Status', models.CharField(max_length=100)),
                ('MECHANIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login')),
            ],
        ),
        migrations.CreateModel(
            name='service_amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Details', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('MECHANIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
        ),
        migrations.AddField(
            model_name='mechanic_request',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
        ),
        migrations.AddField(
            model_name='fuel_provider_request',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
        ),
        migrations.AddField(
            model_name='fuel_provider',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login'),
        ),
        migrations.AddField(
            model_name='fuel_price',
            name='FUEL_PROVIDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.fuel_provider'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='FUEL_PROVIDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.fuel_provider'),
        ),
        migrations.AddField(
            model_name='chat',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
        ),
    ]
