# Generated by Django 2.0.9 on 2025-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0002_auto_20250115_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='FUEL_PROVIDER',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='chat',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login'),
            preserve_default=False,
        ),
    ]
