# Generated by Django 2.0.9 on 2025-01-31 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0003_auto_20250129_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='USER',
        ),
        migrations.AddField(
            model_name='rating',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login'),
            preserve_default=False,
        ),
    ]
