# Generated by Django 2.0.9 on 2025-01-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0004_auto_20250131_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
            preserve_default=False,
        ),
    ]
